settings:
  kafka_connect_url: http://localhost:8083
  client_prefix: "cliente2."
  path_template: ./connectors_template/conn_postgresql_sink_debezium_tmp.json

  datasource:
    jdbc_url: jdbc:postgresql://192.168.96.1:5432/postgres
    user: postgres
    password: postgres
    tables-map:
      - table: products
        pks:
          - id
      - table: products_on_hand
        pks:
          - product_id
      - table: customers
        pks: 
          - id
      - table: orders
        pks: 
          - id
