settings:
  kafka_connect_url: http://localhost:8083
  client_prefix: "cliente1."
  path_template: ./connectors_template/conn_postgresql_sink_debezium_tmp.json

  datasource:
    jdbc_url: jdbc:postgresql://192.168.96.1:5432/postgres
    user: postgres
    password: postgres
    tables-map:
      - table: TB_1
        pks:
          - ID
      - table: TB_2
        pks:
          - ID
      - table: TB_3
        pks: 
          - ID
      - table: TB_4
        pks: 
          - ID
      - table: TB_5
        pks: 
          - ID
      - table: TB_6
        pks: 
          - ID
      - table: TB_9
        pks: 
          - ID
      - table: TB_10
        pks: 
          - ID
