
CREATE TABLE INTCDC.DEBEZIUM_SIGNAL (id VARCHAR(42) PRIMARY KEY, type VARCHAR(32) NOT NULL, data VARCHAR(2048) NULL);

ALTER TABLE INTCDC.DEBEZIUM_SIGNAL ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS

INSERT
	INTO
	INTCDC.DEBEZIUM_SIGNAL
(ID,
	"TYPE",
	"DATA")
VALUES('ad-hoc-13',
'execute-snapshot',
'{"data-collections": ["ORCLCDB.SOURCE_C1.TB_9"],"type":"incremental"}');